### ISSUE TITLE
The GET parameter "ratio" does not work

### ISSUE THREAD

**Issue by Lapeze** [Tanaguru/Contrast-Finder#13]
When you come on contrast finder from Tanaguru issue, the "ratio" parameter does not work.

I test a page on Tanaguru with RGAA 3 level AAA. I see some contrast issues. When I clic on a contrast finder solution link, I'm correctly redirect to Contrast finder with the wrong colors but the ratio isn't 7.

Is it possible to fix it ?

**Comment by fhalna** [comment]
fix !
