### ISSUE TITLE
Allow to choose sorting column via a parameter in URL

### ISSUE THREAD

**Issue by PhilippeVay** [Tanaguru/Contrast-Finder#14]
Hi,

One can already send results given by Contrast-Finder via an URL, example : 

http://contrast-finder.tanaguru.com/result.html?foreground=%236585A5&background=%23FFF&isBackgroundTested=false&ratio=4.5&algo=Rgb

``` foreground=%236585A5
background=%23FFF
isBackgroundTested=false
ratio=4.5
algo=Rgb
```

A nice have would be having results sorted by Distance column or Ratio, etc without any manual action from the user, especially when a link is sent via email or bookmarked for future use.  
Adding a parameter in the URL and managing it when page is loaded is a potential solution (at least if the table sorting script has options for that)

**Comment by fhalna** [comment]
Hi Philippe,

Good idea ! 
we will add this potentiel update in the road map.

Regards.

**Comment by fhalna** [comment]
Hi Philippe,

it's now possible to sort Distance column by parameter asc or desc.

**Comment by fhalna** [comment]
done !
